const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

async function initDatabase() {
  console.log('🔧 Initialisation de la base de données...\n');

  try {
    // Créer l'utilisateur admin
    const adminEmail = 'admin@deutsche-lernen.com';
    const adminPassword = 'admin123';

    let adminUser = await prisma.user.findUnique({
      where: { email: adminEmail }
    });

    if (!adminUser) {
      const adminPasswordHash = await bcrypt.hash(adminPassword, 12);
      adminUser = await prisma.user.create({
        data: {
          email: adminEmail,
          passwordHash: adminPasswordHash,
          role: 'ADMIN'
        }
      });
      console.log('✅ Utilisateur admin créé:', adminEmail);
    } else {
      console.log('ℹ️ Utilisateur admin existe déjà:', adminEmail);
    }

    // Créer un utilisateur de test
    const userEmail = 'user@deutsche-lernen.com';
    const userPassword = 'user123';

    let testUser = await prisma.user.findUnique({
      where: { email: userEmail }
    });

    if (!testUser) {
      const userPasswordHash = await bcrypt.hash(userPassword, 12);
      testUser = await prisma.user.create({
        data: {
          email: userEmail,
          passwordHash: userPasswordHash,
          role: 'USER'
        }
      });
      console.log('✅ Utilisateur test créé:', userEmail);
    } else {
      console.log('ℹ️ Utilisateur test existe déjà:', userEmail);
    }

    // Créer des jeux de base pour les utilisateurs
    const gameTypes = ['quiz', 'mots-croises', 'creativite', 'simulation'];
    const gameModes = ['solo', 'online'];
    const difficulties = ['easy', 'medium', 'hard'];

    const users = [adminUser, testUser];

    for (const user of users) {
      for (const type of gameTypes) {
        for (const mode of gameModes) {
          const existingGame = await prisma.game.findFirst({
            where: {
              userId: user.id,
              type,
              mode
            }
          });

          if (!existingGame) {
            await prisma.game.create({
              data: {
                userId: user.id,
                type,
                mode,
                title: `${type.charAt(0).toUpperCase() + type.slice(1)} - ${mode.charAt(0).toUpperCase() + mode.slice(1)}`,
                description: `Jeu ${type} en mode ${mode}`,
                difficulty: 'medium',
                status: type === 'quiz' ? 'unlocked' : 'locked', // Débloquer les quiz par défaut
                isActive: true,
                metadata: JSON.stringify({
                  created: new Date().toISOString(),
                  autoGenerated: true
                })
              }
            });
          }
        }
      }
    }

    console.log('✅ Jeux de base créés pour tous les utilisateurs');

    // Créer une simulation par défaut pour les salles en ligne
    const defaultSimulation = await prisma.game.findFirst({
      where: {
        type: 'simulation',
        userId: adminUser.id,
        title: 'Conversation générale'
      }
    });

    if (!defaultSimulation) {
      await prisma.game.create({
        data: {
          userId: adminUser.id,
          type: 'simulation',
          mode: 'online',
          title: 'Conversation générale',
          description: 'Discussion ouverte en allemand pour les salles en ligne',
          difficulty: 'medium',
          isActive: true,
          status: 'unlocked',
          metadata: JSON.stringify({
            theme: 'Conversation générale',
            context: 'Discussion libre entre apprenants',
            topics: [
              'Sich vorstellen',
              'Hobbys und Freizeit',
              'Familie und Freunde',
              'Essen und Trinken',
              'Reisen und Urlaub',
              'Schule und Arbeit'
            ]
          })
        }
      });
      console.log('✅ Simulation par défaut créée pour les salles en ligne');
    }

    console.log('\n🎉 Base de données initialisée avec succès!');
    console.log('\n📝 Comptes de test créés:');
    console.log(`   Admin: ${adminEmail} / ${adminPassword}`);
    console.log(`   Utilisateur: ${userEmail} / ${userPassword}`);

  } catch (error) {
    console.error('❌ Erreur lors de l\'initialisation:', error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

// Exécuter le script
initDatabase().catch((error) => {
  console.error('❌ Erreur fatale:', error);
  process.exit(1);
});
